# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Wea1dhnFzrblHnZwNYxQVDCJDi1hbaX
"""

name = "Hemanth"
age = 20
height = 1.75
is_student = True

# Printing all values in a single print statement
print(name, age, height, is_student)

# Using formatted string (f-string)
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")

# Age calculations
age_in_months = age * 12
age_in_days = age * 365
remainder = age % 7
age_square = age ** 2

# Printing results
print("Age in months:", age_in_months)
print("Age in days:", age_in_days)
print("Remainder when age is divided by 7:", remainder)
print("Age squared:", age_square)